In [1]:
import torch

In [3]:
torch.linalg.vector_norm(torch.tensor([[[1.0, 2.0, 3.0]]]), dim=-1)

tensor([[3.7417]])

In [13]:
a = torch.tensor([[1, 1, 1, 1],
                  [1, -1, 0, 1],
                  [1, 0, 0, 1],
                  [1, 1, 1, 1]], dtype=bool)

torch.where(a)

(tensor([0, 0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 3]),
 tensor([0, 1, 2, 3, 0, 1, 3, 0, 3, 0, 1, 2, 3]))

In [14]:
print(a)
a.reshape(-1)[5] = False
print(a)


tensor([[ True,  True,  True,  True],
        [ True,  True, False,  True],
        [ True, False, False,  True],
        [ True,  True,  True,  True]])
tensor([[ True,  True,  True,  True],
        [ True, False, False,  True],
        [ True, False, False,  True],
        [ True,  True,  True,  True]])


In [5]:
b[0][1, 2]

tensor(False)